version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: my_mongo
    ports:
      - "27017:27017"
    networks:
      - my_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    container_name: api-container
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
